name: CrossPlatformBuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.CLIENT }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/rchore
            asset_name: rchore-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/rchore.exe
            asset_name: rchore-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/rchore
            asset_name: rchore-macos

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release --locked

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
